// Agregar aquí cada permiso nuevo junto con la protección de su procedimiento.
// El seed sincroniza este catálogo sin borrar permisos ni asignaciones existentes.
export const PERMISOS = {
  "USERS.VIEW": "Consultar usuarios",
  "USERS.CREATE": "Crear usuarios",
  "USERS.UPDATE": "Editar usuarios",
  "USERS.DISABLE": "Activar y desactivar usuarios",
  "USERS.ASSIGN_ROLE": "Asignar rol a usuarios",
  "USERS.RESET_PASSWORD": "Restablecer contraseñas",
  "ROLES.VIEW": "Consultar roles",
  "ROLES.MANAGE": "Administrar roles y sus permisos",
  "PERMISSIONS.VIEW": "Consultar permisos",
  "EMPLOYEES.VIEW": "Consultar empleados",
  "EMPLOYEES.CREATE": "Crear empleados",
  "EMPLOYEES.UPDATE": "Editar empleados",
  "DEPARTMENTS.VIEW": "Consultar departamentos",
  "DEPARTMENTS.MANAGE": "Administrar departamentos",
  "PAYROLL_PERIODS.VIEW": "Consultar períodos",
  "PAYROLL_PERIODS.CREATE": "Crear períodos",
  "PAYROLL_PERIODS.CLOSE": "Cerrar períodos",
  "ABSENCES.VIEW": "Consultar ausencias",
  "ABSENCES.CREATE": "Crear ausencias",
  "ABSENCES.APPROVE": "Aprobar y rechazar ausencias",
  "PAYROLL.VIEW": "Consultar nóminas",
  "PAYROLL.PROCESS": "Procesar nóminas",
  "PAYROLL.CLOSE": "Cerrar nóminas",
  "PAYROLL_NEWS.VIEW": "Consultar novedades de nómina",
  "PAYROLL_NEWS.MANAGE": "Administrar novedades de nómina",
  "ADVANCES.VIEW": "Consultar anticipos",
  "ADVANCES.PROCESS": "Procesar anticipos",
  "ASSOCIATION.VIEW": "Consultar Asociación Solidarista",
  "ASSOCIATION.MANAGE": "Administrar compras solidaristas",
  "REPORTS.VIEW": "Consultar reportes",
  "ACCOUNTING_POLICY.VIEW": "Consultar póliza contable",
  "SALARY_BOOK.VIEW": "Consultar Libro de Salarios",
  "SETTINGS.VIEW": "Consultar configuración",
  "SETTINGS.MANAGE": "Administrar configuración",
} as const;

export type CodigoPermiso = keyof typeof PERMISOS;
